(() => {
  const KEY='payguard_demo_v01';
  const today=()=>new Date().toISOString().slice(0,10);
  const addMonths=(date,n)=>{const d=new Date(date+'T12:00:00');d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)};
  const cents=v=>Math.round(Number(v||0)*100);
  const overdueDays=due=>Math.max(0,Math.floor((new Date(today())-new Date(due+'T00:00:00'))/86400000));
  const scheduleStatus=s=>s.paid_cents>=s.planned_cents?'PAID':overdueDays(s.due_date)>0?'OVERDUE':s.due_date===today()?'DUE':s.paid_cents>0?'PARTIALLY_PAID':'UPCOMING';
  const seed=()=>{
    const now=today();
    const clients=[
      {id:1,company_id:1,first_name:'Иван',last_name:'Петров',middle_name:'Алексеевич',birth_date:'1994-05-12',phone:'+7 999 111-22-33',email:'ivan@example.test',registration_address:'Москва',manager_id:2,created_at:now},
      {id:2,company_id:1,first_name:'Анна',last_name:'Соколова',middle_name:'Игоревна',birth_date:'1998-10-02',phone:'+7 999 222-33-44',email:'anna@example.test',registration_address:'Москва',manager_id:2,created_at:now},
      {id:3,company_id:1,first_name:'Максим',last_name:'Орлов',middle_name:'Денисович',birth_date:'1991-02-18',phone:'+7 999 333-44-55',email:'max@example.test',registration_address:'Химки',manager_id:2,created_at:now}
    ];
    const contracts=[
      {id:1,company_id:1,client_id:1,manager_id:2,number:'PG-1001',item_description:'iPhone 16 Pro',full_price_cents:14500000,initial_payment_cents:2500000,financed_amount_cents:12000000,markup_percent:10,total_payable_cents:13200000,start_date:addMonths(now,-4),installments:6,status:'ACTIVE'},
      {id:2,company_id:1,client_id:2,manager_id:2,number:'PG-1002',item_description:'MacBook Air',full_price_cents:12000000,initial_payment_cents:2000000,financed_amount_cents:10000000,markup_percent:8,total_payable_cents:10800000,start_date:addMonths(now,-2),installments:6,status:'ACTIVE'},
      {id:3,company_id:1,client_id:3,manager_id:2,number:'PG-1003',item_description:'Телевизор OLED',full_price_cents:9000000,initial_payment_cents:1500000,financed_amount_cents:7500000,markup_percent:12,total_payable_cents:8400000,start_date:addMonths(now,-3),installments:6,status:'ACTIVE'}
    ];
    let sid=1; const schedules=[]; const payments=[]; let pid=1;
    for(const c of contracts){const base=Math.floor(c.total_payable_cents/c.installments);let rem=c.total_payable_cents;for(let i=1;i<=c.installments;i++){const plan=i===c.installments?rem:base;rem-=plan;let paid=0;if(c.id===1&&i<=3)paid=plan;if(c.id===2&&i===1)paid=plan;if(c.id===3&&i===1)paid=Math.round(plan*.35);schedules.push({id:sid++,company_id:1,contract_id:c.id,due_date:addMonths(c.start_date,i),planned_cents:plan,paid_cents:paid});if(paid){payments.push({id:pid++,company_id:1,contract_id:c.id,amount_cents:paid,paid_at:addMonths(c.start_date,i),method:'TRANSFER',created_by:2})}}}
    return {session:null,next:{client:4,contract:4,schedule:sid,payment:pid,audit:2,user:3},companies:[{id:1,name:'ООО «Демо»',plan:'BUSINESS',blocked:0}],users:[{id:1,company_id:1,name:'Александр Волков',email:'owner@demo.local',password:'Demo12345!',role:'OWNER',active:1},{id:2,company_id:1,name:'Мария Смирнова',email:'manager@demo.local',password:'Demo12345!',role:'MANAGER',active:1}],clients,contracts,schedules,payments,audit:[{id:1,company_id:1,user_id:1,action:'DEMO_INITIALIZED',entity_type:'system',entity_id:'demo',created_at:new Date().toLocaleString('ru-RU')}],riskChecks:[]};
  };
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const audit=(s,u,action,type,id)=>s.audit.unshift({id:s.next.audit++,company_id:u.company_id,user_id:u.id,action,entity_type:type,entity_id:String(id),created_at:new Date().toLocaleString('ru-RU')});
  const user=s=>s.users.find(x=>x.id===s.session)||null;
  const json=v=>Promise.resolve(v);
  window.__resetPayGuardDemo=()=>{localStorage.removeItem(KEY);location.reload()};
  window.api=async function(path,opt={}){
    let s=load(); const method=(opt.method||'GET').toUpperCase(); let body={}; try{body=opt.body?JSON.parse(opt.body):{}}catch{}
    const [pathname,qs='']=path.split('?'); const q=new URLSearchParams(qs); const u=user(s);
    const need=()=>{if(!u)throw new Error('Требуется вход')};
    if(method==='POST'&&pathname==='/api/login'){const found=s.users.find(x=>x.email===String(body.email||'').toLowerCase()&&x.password===body.password&&x.active);if(!found)throw new Error('Неверный email или пароль');s.session=found.id;save(s);return {ok:true,role:found.role}}
    if(method==='POST'&&pathname==='/api/register'){if(!body.company||!body.name||!body.email||String(body.password||'').length<8)throw new Error('Заполните поля. Пароль минимум 8 символов.');const cid=Math.max(0,...s.companies.map(x=>x.id))+1;const uid=s.next.user++;s.companies.push({id:cid,name:body.company,plan:'START',blocked:0});s.users.push({id:uid,company_id:cid,name:body.name,email:String(body.email).toLowerCase(),password:body.password,role:'OWNER',active:1});s.session=uid;save(s);return {ok:true}}
    if(method==='POST'&&pathname==='/api/logout'){s.session=null;save(s);return {ok:true}}
    if(method==='GET'&&pathname==='/api/me')return u?{id:u.id,name:u.name,email:u.email,role:u.role,company_id:u.company_id,company_name:s.companies.find(c=>c.id===u.company_id)?.name}:null;
    need(); const cid=u.company_id;
    const schedules=()=>s.schedules.map(x=>({...x,status:scheduleStatus(x)}));
    if(method==='GET'&&pathname==='/api/dashboard'){const ss=schedules().filter(x=>x.company_id===cid);const cs=s.contracts.filter(x=>x.company_id===cid);const cls=s.clients.filter(x=>x.company_id===cid);const stats={clients:cls.length,activeContracts:cs.filter(x=>x.status==='ACTIVE').length,portfolio:cs.reduce((a,x)=>a+x.total_payable_cents,0),remaining:ss.reduce((a,x)=>a+x.planned_cents-x.paid_cents,0),overdue:ss.filter(x=>x.status==='OVERDUE').reduce((a,x)=>a+x.planned_cents-x.paid_cents,0)};const join=x=>{const c=cs.find(c=>c.id===x.contract_id),cl=cls.find(cl=>cl.id===c.client_id);return {...x,number:c.number,client_id:cl.id,first_name:cl.first_name,last_name:cl.last_name,phone:cl.phone,overdue_days:overdueDays(x.due_date)}};return {stats,upcoming:ss.filter(x=>x.status!=='PAID').sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,8).map(join),overdue:ss.filter(x=>x.status==='OVERDUE').sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,10).map(join)}}
    if(method==='GET'&&pathname==='/api/clients'){const query=(q.get('q')||'').toLowerCase();return s.clients.filter(x=>x.company_id===cid&&(!query||`${x.first_name} ${x.last_name} ${x.phone}`.toLowerCase().includes(query))).map(x=>({...x,manager_name:s.users.find(u=>u.id===x.manager_id)?.name||'—',contracts:s.contracts.filter(c=>c.client_id===x.id&&c.company_id===cid).length}))}
    if(method==='POST'&&pathname==='/api/clients'){if(!body.first_name||!body.last_name)throw new Error('Имя и фамилия обязательны');const id=s.next.client++;s.clients.push({id,company_id:cid,manager_id:u.id,created_at:today(),...body});audit(s,u,'CLIENT_CREATE','client',id);save(s);return {id}}
    let m=pathname.match(/^\/api\/clients\/(\d+)$/);if(method==='GET'&&m){const cl=s.clients.find(x=>x.id===+m[1]&&x.company_id===cid);if(!cl)throw new Error('Клиент не найден');const cs=s.contracts.filter(c=>c.company_id===cid&&c.client_id===cl.id).map(c=>({...c,remaining_cents:s.schedules.filter(x=>x.contract_id===c.id).reduce((a,x)=>a+x.planned_cents-x.paid_cents,0)}));return {...cl,contracts:cs}}
    if(method==='GET'&&pathname==='/api/contracts'){const ss=schedules();return s.contracts.filter(c=>c.company_id===cid).map(c=>{const cl=s.clients.find(x=>x.id===c.client_id),own=ss.filter(x=>x.contract_id===c.id);return {...c,first_name:cl.first_name,last_name:cl.last_name,remaining_cents:own.reduce((a,x)=>a+x.planned_cents-x.paid_cents,0),overdue_cents:own.filter(x=>x.status==='OVERDUE').reduce((a,x)=>a+x.planned_cents-x.paid_cents,0)}})}
    if(method==='POST'&&pathname==='/api/contracts'){const cl=s.clients.find(x=>x.id===Number(body.client_id)&&x.company_id===cid);if(!cl)throw new Error('Клиент не найден');const price=cents(body.full_price),initial=cents(body.initial_payment);if(initial>price)throw new Error('Первоначальный взнос больше стоимости');const financed=price-initial,total=Math.round(financed*(1+Number(body.markup_percent||0)/100)),inst=Math.max(1,Number(body.installments||1)),id=s.next.contract++;const c={id,company_id:cid,client_id:cl.id,manager_id:u.id,number:body.number,item_description:body.item_description,full_price_cents:price,initial_payment_cents:initial,financed_amount_cents:financed,markup_percent:Number(body.markup_percent||0),total_payable_cents:total,start_date:body.start_date,installments:inst,status:'ACTIVE'};s.contracts.push(c);const base=Math.floor(total/inst);let rem=total;for(let i=1;i<=inst;i++){const plan=i===inst?rem:base;rem-=plan;s.schedules.push({id:s.next.schedule++,company_id:cid,contract_id:id,due_date:addMonths(body.start_date,i),planned_cents:plan,paid_cents:0})}audit(s,u,'CONTRACT_CREATE','contract',id);save(s);return {id}}
    m=pathname.match(/^\/api\/contracts\/(\d+)$/);if(method==='GET'&&m){const c=s.contracts.find(x=>x.id===+m[1]&&x.company_id===cid);if(!c)throw new Error('Договор не найден');return {...c,client:s.clients.find(x=>x.id===c.client_id),schedule:schedules().filter(x=>x.contract_id===c.id).map(x=>({...x,overdue_days:overdueDays(x.due_date)})),payments:s.payments.filter(x=>x.contract_id===c.id)}}
    m=pathname.match(/^\/api\/contracts\/(\d+)\/payments$/);if(method==='POST'&&m){const c=s.contracts.find(x=>x.id===+m[1]&&x.company_id===cid);if(!c)throw new Error('Договор не найден');let amount=cents(body.amount);if(amount<=0)throw new Error('Сумма должна быть больше нуля');const open=s.schedules.filter(x=>x.contract_id===c.id&&x.paid_cents<x.planned_cents).sort((a,b)=>a.due_date.localeCompare(b.due_date));const rem=open.reduce((a,x)=>a+x.planned_cents-x.paid_cents,0);if(amount>rem)throw new Error('Переплата в MVP не поддерживается. Укажите сумму не больше остатка.');s.payments.push({id:s.next.payment++,company_id:cid,contract_id:c.id,amount_cents:amount,paid_at:body.paid_at||today(),method:body.method||'TRANSFER',created_by:u.id});let left=amount;for(const x of open){const n=Math.min(left,x.planned_cents-x.paid_cents);x.paid_cents+=n;left-=n;if(left<=0)break}audit(s,u,'PAYMENT_CREATE','contract',c.id);save(s);return {ok:true}}
    if(method==='GET'&&pathname==='/api/overdue'){const ss=schedules().filter(x=>x.company_id===cid&&x.status==='OVERDUE');return ss.map(x=>{const c=s.contracts.find(c=>c.id===x.contract_id),cl=s.clients.find(cl=>cl.id===c.client_id);return {...x,number:c.number,client_id:cl.id,first_name:cl.first_name,last_name:cl.last_name,phone:cl.phone,manager_name:s.users.find(z=>z.id===c.manager_id)?.name||'—',overdue_days:overdueDays(x.due_date)}})}
    if(method==='POST'&&pathname==='/api/risk-check'){const norm=v=>String(v||'').toLowerCase().replace(/\s+/g,' ').trim(),phone=v=>String(v||'').replace(/\D/g,'').slice(-10);const matches=s.clients.filter(x=>(norm(x.last_name)===norm(body.last_name)&&norm(x.first_name)===norm(body.first_name)&&x.birth_date===body.birth_date)||(phone(x.phone)&&phone(x.phone)===phone(body.phone)&&x.birth_date===body.birth_date));let completed=0,o7=0,o30=0,o60=0,active=false;for(const cl of matches){for(const c of s.contracts.filter(c=>c.client_id===cl.id)){const ss=s.schedules.filter(x=>x.contract_id===c.id);if(ss.length&&ss.every(x=>x.paid_cents>=x.planned_cents))completed++;for(const x of ss){const d=overdueDays(x.due_date);if(d>=7)o7++;if(d>=30)o30++;if(d>=60)o60++;if(d>0&&x.paid_cents<x.planned_cents)active=true}}}let score=Math.min(100,Math.max(0,(active?20:0)+o7*5+o30*10+o60*15-completed*4));const level=score<30?'LOW':score<60?'MEDIUM':score<80?'HIGH':'VERY_HIGH';const reasons=[];if(active)reasons.push('Есть активная просрочка');if(o30)reasons.push(`Просрочек 30+ дней: ${o30}`);if(o60)reasons.push(`Просрочек 60+ дней: ${o60}`);if(completed)reasons.push(`Успешно закрытых договоров: ${completed}`);if(!reasons.length)reasons.push('Негативных сигналов в демо-данных не найдено');audit(s,u,'RISK_CHECK','person','demo');save(s);return {found:matches.length>0,known_profiles:matches.length,completed_contracts:completed,overdue7:o7,overdue30:o30,overdue60:o60,active_overdue:active,score,level,reasons,disclaimer:'Демо-скоринг. Не является кредитным рейтингом или заключением БКИ.'}}
    if(method==='GET'&&pathname==='/api/team')return s.users.filter(x=>x.company_id===cid).map(({password,...x})=>x);
    if(method==='POST'&&pathname==='/api/team'){const id=s.next.user++;s.users.push({id,company_id:cid,name:body.name,email:String(body.email).toLowerCase(),password:body.password,role:body.role,active:1,created_at:today()});audit(s,u,'TEAM_MEMBER_CREATE','user',id);save(s);return {id}}
    if(method==='GET'&&pathname==='/api/audit')return s.audit.filter(x=>x.company_id===cid).map(x=>({...x,user_name:s.users.find(u=>u.id===x.user_id)?.name||'System'}));
    if(method==='GET'&&pathname==='/api/reports'){const map={};for(const p of s.payments.filter(x=>x.company_id===cid)){const month=p.paid_at.slice(0,7);map[month]??={month,amount_cents:0,payments:0};map[month].amount_cents+=p.amount_cents;map[month].payments++}return {monthly:Object.values(map).sort((a,b)=>b.month.localeCompare(a.month))}}
    if(method==='GET'&&pathname==='/api/admin/companies')return s.companies.map(c=>({...c,users:s.users.filter(x=>x.company_id===c.id).length,clients:s.clients.filter(x=>x.company_id===c.id).length,contracts:s.contracts.filter(x=>x.company_id===c.id).length}));
    throw new Error('Демо-endpoint не найден');
  };
})();
